### ISSUE TITLE
Dockerfile pinned to 3.1 .NET SDK causes failures to build on docker.

### ISSUE THREAD

**Issue by jaydestro** [microsoft/TailwindTraders-Website#96] opened 2020-02-27 08:33 UTC
```ARG sdkTag=3.0
ARG runtimeTag=3.0
ARG image=mcr.microsoft.com/dotnet/core/aspnet
ARG sdkImage=mcr.microsoft.com/dotnet/core/sdk
```

 unless there is a pinned SDK then 3.x should build anything. 

works when i set sdk and runtime to 2.1

essentially work done between 08-31-2019 till now was done without build tests?  

```
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restore completed in 46.06 ms for /app/Tailwind.Traders.Web.csproj.
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '2.0.7' was not found.
    - The following frameworks were found:
        3.0.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  You can resolve the problem by installing the specified framework and/or SDK.
  The .NET Core frameworks can be found at:
    - https://aka.ms/dotnet-download
/root/.nuget/packages/microsoft.aspnetcore.razor.design/2.1.2/build/netstandard2.0/Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error : rzc discover exited with code 150. [/app/Tailwind.Traders.Web.csproj]
Build FAILED.
/root/.nuget/packages/microsoft.aspnetcore.razor.design/2.1.2/build/netstandard2.0/Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error : rzc discover exited with code 150. [/app/Tailwind.Traders.Web.csproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:24.59
The command '/bin/sh -c dotnet build' returned a non-zero code: 1
2020/02/26 16:30:24 Container failed during run: build. No retries remaining.
failed to run step ID: build: exit status 1
Run ID: ca5 failed after 4m9s. Error: failed during run, err: exit status 1
Run failed
```

**Comment by ivilches** [comment] 2020-03-25 11:15
The problem is solved by your PR #97 'Update Dockerfile' 
This issue should be closed as soon as possible :)

**Closed** 2020-03-25 17:04 UTC
